name: GitHub Action for Portfolio
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      command:
        description: "Windows command to run"
        required: true
        default: 'echo "Hello from Windows!"'
        type: string

jobs:
  run-windows-command:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run 5 Windows Commands in Succession
        shell: cmd
        run: |
          echo "=== Command 1: Show current directory ==="
          cd
          echo.
          echo "=== Command 2: List directory contents ==="
          dir
          echo.
          echo "=== Command 3: Show current user ==="
          whoami
          echo.
          echo "=== Command 4: Show date and time ==="
          date /t && time /t
